# Generated by Django 5.1.7 on 2026-05-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompizza',
            name='base',
        ),
        migrations.RemoveField(
            model_name='custompizza',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='custompizza',
            name='sauce',
        ),
        migrations.AddField(
            model_name='custompizza',
            name='composition',
            field=models.JSONField(default=dict),
        ),
    ]
